<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <OutputType>WinExe</OutputType>
      <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
      <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
      <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
      <WindowsPackageType>None</WindowsPackageType>
      <EnableMsixTooling>true</EnableMsixTooling>
      <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
      <UseWinUI>true</UseWinUI>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
      <Configurations>Debug;Release</Configurations>
      <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' And ('$(Platform)' == '' Or '$(Platform)' == 'AnyCPU')">win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="misc\**" />
    <Compile Remove="settings\**" />
    <EmbeddedResource Remove="misc\**" />
    <EmbeddedResource Remove="settings\**" />
    <None Remove="misc\**" />
    <None Remove="settings\**" />
    <Page Remove="misc\**" />
    <Page Remove="settings\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="H.NotifyIcon.WinUI" Version="2.4.1" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.5.1" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="App.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="MainWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <PRIResource Remove="misc\**" />
  </ItemGroup>

  <ItemGroup>
    <PRIResource Remove="settings\**" />
  </ItemGroup>

</Project>
